### ISSUE TITLE
Add a issue template 

### ISSUE THREAD

**Issue by to09** [AcademySoftwareFoundation/opencue.io#169]
Add a custom issue template to help them describing issue more clearly.

**Comment by bcipriano** [comment]
Very good idea!

Unlike [the main OpenCue issue templates](https://github.com/AcademySoftwareFoundation/OpenCue/tree/master/.github/ISSUE_TEMPLATE), I think we only really need one predefined type of issue, to cover any and all documentation updates.

All other issues should be logged instead under the main OpenCue repo. Maybe this repo's issue template could contain some helpful text redirecting folks back to [OpenCue/issues/new/choose](https://github.com/AcademySoftwareFoundation/OpenCue/issues/new/choose) for non-documentation issues.

**Comment by to09** [comment]
I am interested in this issue, Please assign it to me.

**Comment by sharifsalah** [comment]
Thanks @to09! I've assigned you the issue.

**Comment by to09** [comment]
Thanks for assigning the issue.
Is a question-based template is good for this?

**Comment by bcipriano** [comment]
@to09 I'm not really sure what you mean by "question-based template". Could you clarify?

**Comment by to09** [comment]
Sure, 
I mean to say that question-based-template like this:
When does this occur?
Where on the platform does it happen?
How do we replicate the issue?
Expected behavior (i.e. solution)
Other Comments

**Comment by bcipriano** [comment]
Ah ok I see.

I think since these will be documentation updates, there aren't many different pieces of information we need. For example we won't need to replicate the issue, there shouldn't be differences between platforms.

I would tend to keep it pretty simple, something like the main repo's [enhancement](https://raw.githubusercontent.com/AcademySoftwareFoundation/OpenCue/master/.github/ISSUE_TEMPLATE/enhancement.md) or [process](https://raw.githubusercontent.com/AcademySoftwareFoundation/OpenCue/master/.github/ISSUE_TEMPLATE/process.md) templates.

**Comment by to09** [comment]
Ok, thanks I have started working on this issue.
