### ISSUE TITLE
Streamlining setting up a local instance of documentation using Hugo #214

### ISSUE THREAD

**Issue by saki-osive** [AcademySoftwareFoundation/opencue.io#215]
As a beginner to this project, setting up a local instance using Hugo had me some tweaks to do, so I have added changes in the readme.md file which make it very easy and simple to get a local instance running on any system from the get go.

Although all steps have been covered, they aren't at all ordered and just not the way to go for a beginner to this project, wishing to contribute.

The changes have been made keeping in mind that the new contributors to the project must have the very first step in their journey, i.e. "Setting up the local instance of the docs" easy and simple without any tweaking being needed.

**Comment by sharifsalah** [comment]
In the pull request, you suggest users install the following packages:

- autoprefixer
- postcss-cli

Could you please add more detail about why these are required for local development?

If they are required for production (which I don't think is the case), then I think it makes sense to add them to `package-lock.json`. If they're *only* required for local development, then I think we would want to instruct users to install without modifying dependencies:

npm install <package-name>

(Without the -D --save options)

Otherwise, some users are probably going to end up including the package-lock.json changes in their pull requests?

**Comment by saki-osive** [comment]
Hi, without installing the following packages,

- autoprefixer
- postcss-cli

 the local instance loaded but was missing some of the SCSS components which made the webpages look odd. However after adding these, the problem was fixed and a normal instance was loaded as it does on the page https://www.opencue.io/. Due to this, I requested to add those packages in the documentation.

Yes, the ```-D --save``` options should be removed from the commands. I have removed them from the pull request, please have a look.
