### ISSUE TITLE
Some staging site links point back to main opencue.io.

### ISSUE THREAD

**Issue by bcipriano** [AcademySoftwareFoundation/opencue.io#76]
I noticed this on https://deploy-preview-75--elated-haibt-1b47ff.netlify.com/docs/.

The main body text "OpenCue getting started guide" is a link, but it links back to https://www.opencue.io/docs/getting-started/ instead of the same page on the staged version.

However the TOC links on the left-hand side of the page work fine.

**Comment by sharifsalah** [comment]
Thanks for reporting! Yes I noticed this yesterday but hadn't got round to investigating the cause or reporting it. Looking at it, I think this is related to the [change Docsy recently made]( https://github.com/google/docsy/pull/67) as a result of a feature request to auto-generate index pages. (which saves us work to manage the indexes manually)

Specifically, it's the changes in [section-index.html](https://github.com/google/docsy/blob/ce710eed23d600825c0c5a4cba586dab571bd4da/layouts/partials/section-index.html) to generate the link as follows:

```html
                    <li><a href="{{ .Permalink }}">{{- .Title -}}</a></li>
```

I think we need to update `.Permalink` to `.RelPermalink` to make the index behave the same as the left-hand sidebar menu.

This bug is going to affect every OSS project using Docsy, so I'll file a bug upstream and reference it here. If we can fix it quickly then I'll wait to pull the changes from Docsy, otherwise I can temporarily fix it for opencue.io with an override if we feel it's urgent / confusing.

**Comment by sharifsalah** [comment]
Reported in https://github.com/google/docsy/issues/103

**Comment by sharifsalah** [comment]
Fixed upstream in https://github.com/google/docsy/pull/104

Will need to update to the latest version of Docsy to apply the fix.
